version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: tutoron-backend
    volumes:
      - ./server:/var/www
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - tutoron-net

  mysql:
    image: mysql:8.0
    container_name: tutoron-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorongpt
      MYSQL_USER: ghady
      MYSQL_PASSWORD: ghady123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tutoron-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tutoron-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ghady
      PMA_PASSWORD: ghady123
    depends_on:
      - mysql
    networks:
      - tutoron-net

volumes:
  mysql_data:

networks:
  tutoron-net:
    driver: bridge
